print("First 10 letters of alpabet in lowercase\n")
t=head(letters,10)
print(t)
print("Last 10 letters of alphabet in upppercase\n")
a=tail(LETTERS,10)
print(a)
cat(22,"between",24,"alphabets are")
e=tail(LETTERS[22:24])
print(e)